### ISSUE TITLE
Saving Media Credit settings throws an error

### ISSUE THREAD

**Issue by graham73may** [mundschenk-at/media-credit#19]
If I press save on the page: /wp-admin/options-media.php#media-credit, the following errors appear:

`
Notice: Array to string conversion in /home/abcde/public_html/wp-includes/formatting.php on line 1025

Notice: Array to string conversion in /home/abcde/public_html/wp-includes/formatting.php on line 1025
`

Wordpress 4.6
Media Credit 3.1.1

**Comment by mundschenk-at** [comment]
@graham73may What character encoding are you using? Could you attach a screenshot of the `options-media.php`?

**Comment by mundschenk-at** [comment]
@graham73may Are you still experiencing this?

**Comment by graham73may** [comment]
Hi, sorry for the delay. This one kept getting pushed to the bottom of the to do list. I've just set myself a reminder to check this when I'm back in the office on Wednesday.

**Comment by graham73may** [comment]
Hi @mundschenk-at I've just tried to replicate this again on an up to date Wordpress with the plugin and all appears to be working as expected now. :). Thanks!
