### ISSUE TITLE
Allow to change / set the default media credit

### ISSUE THREAD

**Issue by E-VANCE** [mundschenk-at/media-credit#33]
Hi there,

I was wondering if it is possible to set a default media credit string or to overwrite the existing logic via a filter or such since the default always reads "User SEPARATOR Organization" and we would like to be able to just have it always read X by default and then we can set it differently if need be...

Any chance of hooking into that?

Thanks!

**Comment by mundschenk-at** [comment]
Not at the moment, but I'll look at it for future releases.

**Comment by mundschenk-at** [comment]
@E-VANCE Would like to be able to set the actual credit string or just the placeholder value? And you don't want to have the user in there, right? (Because you could always just leave separator and organization blank in the settings.)

**Comment by E-VANCE** [comment]
@mundschenk-at The idea was to be able to set the actual credit string – then all images uploaded have a default credit value added and we would only need to change it in the cases where not applicable. That would actually be much less work since the default applies in > 80 % and we could eliminate any input / type errors. And yes, we wouldn't want the user in there...
